version: "3.10"

networks:
  verim_network:
    name: verim_network

services:
  db:
    image: postgres:15.4
    container_name: ${CONTAINER_PREFIX}-db
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
      - ${MAIN_PATH}/configs/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      AUTH_POSTGRES_USER: ${AUTH_DB_USER}
      AUTH_POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      AUTH_POSTGRES_DB: ${AUTH_DB_NAME}
      TEST_AUTH_POSTGRES_USER: ${TEST_AUTH_DB_USER}
      TEST_AUTH_POSTGRES_PASSWORD: ${TEST_AUTH_DB_PASSWORD}
      TEST_AUTH_POSTGRES_DB: ${TEST_AUTH_DB_NAME}
      PUBLISHER_POSTGRES_USER: ${PUBLISHER_DB_USER}
      PUBLISHER_POSTGRES_PASSWORD: ${PUBLISHER_DB_PASSWORD}
      PUBLISHER_POSTGRES_DB: ${PUBLISHER_DB_NAME}
      TEST_PUBLISHER_POSTGRES_USER: ${TEST_PUBLISHER_DB_USER}
      TEST_PUBLISHER_POSTGRES_PASSWORD: ${TEST_PUBLISHER_DB_PASSWORD}
      TEST_PUBLISHER_POSTGRES_DB: ${TEST_PUBLISHER_DB_NAME}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
    networks:
      - verim_network
    ports:
      - "127.0.0.1:7433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.0
    container_name: ${CONTAINER_PREFIX}-redis
    networks:
      - verim_network
    ports:
      - "13379:6379"
    volumes:
      - verim_redis_data:/var/lib/redis/data/
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: verim-rabbitmq
    container_name: ${CONTAINER_PREFIX}-rabbitmq
    volumes:
      - verim_rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - verim_network
    restart: on-failure
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  gateway:
    container_name: ${CONTAINER_PREFIX}-gateway
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    working_dir: ${DEFAULT_SERVICE_DIR}
    env_file:
      - .env
    volumes:
      # app dir
      - ./gateway/:${DEFAULT_SERVICE_DIR}
      # web stuff
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
      # protobufs
      - ./protobufs/compiled/auth_pb2_grpc.py:${DEFAULT_SERVICE_DIR}/auth_pb2_grpc.py
      - ./protobufs/compiled/auth_pb2.py:${DEFAULT_SERVICE_DIR}/auth_pb2.py
      - ./protobufs/compiled/auth_grpc_typed.py:${DEFAULT_SERVICE_DIR}/auth_grpc_typed.py
      - ./protobufs/compiled/publisher_pb2_grpc.py:${DEFAULT_SERVICE_DIR}/publisher_pb2_grpc.py
      - ./protobufs/compiled/publisher_pb2.py:${DEFAULT_SERVICE_DIR}/publisher_pb2.py
      - ./protobufs/compiled/publisher_grpc_typed.py:${DEFAULT_SERVICE_DIR}/publisher_grpc_typed.py
      # common stuff
      - ./mounts/config/grpc.py:${DEFAULT_SERVICE_DIR}/config/grpc.py
      - ./mounts/config/i18n.py:${DEFAULT_SERVICE_DIR}/config/i18n.py
      - ./mounts/config/mail.py:${DEFAULT_SERVICE_DIR}/config/mail.py
      - ./mounts/utils/app.py:${DEFAULT_SERVICE_DIR}/utils/app.py
      - ./mounts/utils/email.py:${DEFAULT_SERVICE_DIR}/utils/email.py
      - ./mounts/utils/exceptions.py:${DEFAULT_SERVICE_DIR}/utils/exceptions.py
      - ./mounts/utils/decorators.py:${DEFAULT_SERVICE_DIR}/utils/decorators.py
      - ./mounts/utils/pygettext.py:${DEFAULT_SERVICE_DIR}/utils/pygettext.py
      - ./mounts/utils/routing.py:${DEFAULT_SERVICE_DIR}/utils/routing.py
      - ./mounts/utils/schemas.py:${DEFAULT_SERVICE_DIR}/utils/schemas.py
      - ./mounts/utils/shortcuts.py:${DEFAULT_SERVICE_DIR}/utils/shortcuts.py
      - ./mounts/utils/test.py:${DEFAULT_SERVICE_DIR}/utils/test.py
      - ./mounts/utils/time.py:${DEFAULT_SERVICE_DIR}/utils/time.py
      - ./mounts/utils/pagination.py:${DEFAULT_SERVICE_DIR}/utils/pagination.py
      - ./mounts/utils/logging.py:${DEFAULT_SERVICE_DIR}/utils/logging.py
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - verim_network
    restart: always

  auth:
    container_name: ${CONTAINER_PREFIX}-auth
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    working_dir: ${DEFAULT_SERVICE_DIR}
    env_file:
      - .env
    volumes:
      # app dir
      - ./auth/:${DEFAULT_SERVICE_DIR}
      # web stuff
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
      # protobufs
      - ./protobufs/compiled/auth_pb2_grpc.py:${DEFAULT_SERVICE_DIR}/auth_pb2_grpc.py
      - ./protobufs/compiled/auth_pb2.py:${DEFAULT_SERVICE_DIR}/auth_pb2.py
      - ./protobufs/compiled/auth_grpc_typed.py:${DEFAULT_SERVICE_DIR}/auth_grpc_typed.py
      - ./protobufs/compiled/publisher_pb2_grpc.py:${DEFAULT_SERVICE_DIR}/publisher_pb2_grpc.py
      - ./protobufs/compiled/publisher_pb2.py:${DEFAULT_SERVICE_DIR}/publisher_pb2.py
      - ./protobufs/compiled/publisher_grpc_typed.py:${DEFAULT_SERVICE_DIR}/publisher_grpc_typed.py
      # common stuff
      - ./mounts/config/db.py:${DEFAULT_SERVICE_DIR}/config/db.py
      - ./mounts/config/grpc.py:${DEFAULT_SERVICE_DIR}/config/grpc.py
      - ./mounts/config/i18n.py:${DEFAULT_SERVICE_DIR}/config/i18n.py
      - ./mounts/config/mail.py:${DEFAULT_SERVICE_DIR}/config/mail.py
      - ./mounts/utils/email.py:${DEFAULT_SERVICE_DIR}/utils/email.py
      - ./mounts/utils/exceptions.py:${DEFAULT_SERVICE_DIR}/utils/exceptions.py
      - ./mounts/utils/decorators.py:${DEFAULT_SERVICE_DIR}/utils/decorators.py
      - ./mounts/utils/pygettext.py:${DEFAULT_SERVICE_DIR}/utils/pygettext.py
      - ./mounts/utils/random.py:${DEFAULT_SERVICE_DIR}/utils/random.py
      - ./mounts/utils/repo.py:${DEFAULT_SERVICE_DIR}/utils/repo.py
      - ./mounts/utils/schemas.py:${DEFAULT_SERVICE_DIR}/utils/schemas.py
      - ./mounts/utils/shortcuts.py:${DEFAULT_SERVICE_DIR}/utils/shortcuts.py
      - ./mounts/utils/test.py:${DEFAULT_SERVICE_DIR}/utils/test.py
      - ./mounts/utils/time.py:${DEFAULT_SERVICE_DIR}/utils/time.py
      - ./mounts/utils/pagination.py:${DEFAULT_SERVICE_DIR}/utils/pagination.py
      - ./mounts/utils/logging.py:${DEFAULT_SERVICE_DIR}/utils/logging.py
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50051:50051"
    networks:
      - verim_network
    restart: always

  publisher:
    container_name: ${CONTAINER_PREFIX}-publisher
    build:
      context: .
      dockerfile: ./publisher/Dockerfile
    working_dir: ${DEFAULT_SERVICE_DIR}
    env_file:
      - .env
    volumes:
      # app dir
      - ./publisher/:${DEFAULT_SERVICE_DIR}
      # web stuff
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
      # protobufs
      - ./protobufs/compiled/auth_pb2_grpc.py:${DEFAULT_SERVICE_DIR}/auth_pb2_grpc.py
      - ./protobufs/compiled/auth_pb2.py:${DEFAULT_SERVICE_DIR}/auth_pb2.py
      - ./protobufs/compiled/auth_grpc_typed.py:${DEFAULT_SERVICE_DIR}/auth_grpc_typed.py
      - ./protobufs/compiled/publisher_pb2_grpc.py:${DEFAULT_SERVICE_DIR}/publisher_pb2_grpc.py
      - ./protobufs/compiled/publisher_pb2.py:${DEFAULT_SERVICE_DIR}/publisher_pb2.py
      - ./protobufs/compiled/publisher_grpc_typed.py:${DEFAULT_SERVICE_DIR}/publisher_grpc_typed.py
      # common stuff
      - ./mounts/config/db.py:${DEFAULT_SERVICE_DIR}/config/db.py
      - ./mounts/config/grpc.py:${DEFAULT_SERVICE_DIR}/config/grpc.py
      - ./mounts/config/i18n.py:${DEFAULT_SERVICE_DIR}/config/i18n.py
      - ./mounts/config/mail.py:${DEFAULT_SERVICE_DIR}/config/mail.py
      - ./mounts/utils/email.py:${DEFAULT_SERVICE_DIR}/utils/email.py
      - ./mounts/utils/exceptions.py:${DEFAULT_SERVICE_DIR}/utils/exceptions.py
      - ./mounts/utils/decorators.py:${DEFAULT_SERVICE_DIR}/utils/decorators.py
      - ./mounts/utils/pygettext.py:${DEFAULT_SERVICE_DIR}/utils/pygettext.py
      - ./mounts/utils/random.py:${DEFAULT_SERVICE_DIR}/utils/random.py
      - ./mounts/utils/repo.py:${DEFAULT_SERVICE_DIR}/utils/repo.py
      - ./mounts/utils/schemas.py:${DEFAULT_SERVICE_DIR}/utils/schemas.py
      - ./mounts/utils/shortcuts.py:${DEFAULT_SERVICE_DIR}/utils/shortcuts.py
      - ./mounts/utils/test.py:${DEFAULT_SERVICE_DIR}/utils/test.py
      - ./mounts/utils/time.py:${DEFAULT_SERVICE_DIR}/utils/time.py
      - ./mounts/utils/pagination.py:${DEFAULT_SERVICE_DIR}/utils/pagination.py
      - ./mounts/utils/logging.py:${DEFAULT_SERVICE_DIR}/utils/logging.py
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50052:50052"
    networks:
      - verim_network
    restart: always

  celery-worker:
    container_name: ${CONTAINER_PREFIX}-celery-worker
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    command: sh -c "celery -A config.celery.app worker -l debug"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      # app dir
      - ./gateway/:${DEFAULT_SERVICE_DIR}
      # web stuff
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
      # protobufs
      - ./protobufs/compiled/auth_pb2_grpc.py:${DEFAULT_SERVICE_DIR}/auth_pb2_grpc.py
      - ./protobufs/compiled/auth_pb2.py:${DEFAULT_SERVICE_DIR}/auth_pb2.py
      - ./protobufs/compiled/auth_grpc_typed.py:${DEFAULT_SERVICE_DIR}/auth_grpc_typed.py
      - ./protobufs/compiled/publisher_pb2_grpc.py:${DEFAULT_SERVICE_DIR}/publisher_pb2_grpc.py
      - ./protobufs/compiled/publisher_pb2.py:${DEFAULT_SERVICE_DIR}/publisher_pb2.py
      - ./protobufs/compiled/publisher_grpc_typed.py:${DEFAULT_SERVICE_DIR}/publisher_grpc_typed.py
      # common stuff
      - ./mounts/config/grpc.py:${DEFAULT_SERVICE_DIR}/config/grpc.py
      - ./mounts/config/i18n.py:${DEFAULT_SERVICE_DIR}/config/i18n.py
      - ./mounts/config/mail.py:${DEFAULT_SERVICE_DIR}/config/mail.py
      - ./mounts/utils/app.py:${DEFAULT_SERVICE_DIR}/utils/app.py
      - ./mounts/utils/exceptions.py:${DEFAULT_SERVICE_DIR}/utils/exceptions.py
      - ./mounts/utils/decorators.py:${DEFAULT_SERVICE_DIR}/utils/decorators.py
      - ./mounts/utils/pygettext.py:${DEFAULT_SERVICE_DIR}/utils/pygettext.py
      - ./mounts/utils/routing.py:${DEFAULT_SERVICE_DIR}/utils/routing.py
      - ./mounts/utils/schemas.py:${DEFAULT_SERVICE_DIR}/utils/schemas.py
      - ./mounts/utils/shortcuts.py:${DEFAULT_SERVICE_DIR}/utils/shortcuts.py
      - ./mounts/utils/test.py:${DEFAULT_SERVICE_DIR}/utils/test.py
      - ./mounts/utils/time.py:${DEFAULT_SERVICE_DIR}/utils/time.py
      - ./mounts/utils/pagination.py:${DEFAULT_SERVICE_DIR}/utils/pagination.py
      - ./mounts/utils/logging.py:${DEFAULT_SERVICE_DIR}/utils/logging.py
    networks:
      - verim_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "celery inspect ping --destination celery@$$HOSTNAME"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery-beat:
    container_name: ${CONTAINER_PREFIX}-celery-beat
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    command: sh -c "celery -A config.celery.app beat -l debug"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      # app dir
      - ./gateway/:${DEFAULT_SERVICE_DIR}
      # web stuff
      - ${STATIC_PATH}:/static
      - ${MEDIA_PATH}:/media
      - ${LOG_PATH}:/logs
      # protobufs
      - ./protobufs/compiled/auth_pb2_grpc.py:${DEFAULT_SERVICE_DIR}/auth_pb2_grpc.py
      - ./protobufs/compiled/auth_pb2.py:${DEFAULT_SERVICE_DIR}/auth_pb2.py
      - ./protobufs/compiled/auth_grpc_typed.py:${DEFAULT_SERVICE_DIR}/auth_grpc_typed.py
      - ./protobufs/compiled/publisher_pb2_grpc.py:${DEFAULT_SERVICE_DIR}/publisher_pb2_grpc.py
      - ./protobufs/compiled/publisher_pb2.py:${DEFAULT_SERVICE_DIR}/publisher_pb2.py
      - ./protobufs/compiled/publisher_grpc_typed.py:${DEFAULT_SERVICE_DIR}/publisher_grpc_typed.py
      # common stuff
      - ./mounts/config/grpc.py:${DEFAULT_SERVICE_DIR}/config/grpc.py
      - ./mounts/config/i18n.py:${DEFAULT_SERVICE_DIR}/config/i18n.py
      - ./mounts/config/mail.py:${DEFAULT_SERVICE_DIR}/config/mail.py
      - ./mounts/utils/app.py:${DEFAULT_SERVICE_DIR}/utils/app.py
      - ./mounts/utils/exceptions.py:${DEFAULT_SERVICE_DIR}/utils/exceptions.py
      - ./mounts/utils/decorators.py:${DEFAULT_SERVICE_DIR}/utils/decorators.py
      - ./mounts/utils/pygettext.py:${DEFAULT_SERVICE_DIR}/utils/pygettext.py
      - ./mounts/utils/routing.py:${DEFAULT_SERVICE_DIR}/utils/routing.py
      - ./mounts/utils/schemas.py:${DEFAULT_SERVICE_DIR}/utils/schemas.py
      - ./mounts/utils/shortcuts.py:${DEFAULT_SERVICE_DIR}/utils/shortcuts.py
      - ./mounts/utils/test.py:${DEFAULT_SERVICE_DIR}/utils/test.py
      - ./mounts/utils/time.py:${DEFAULT_SERVICE_DIR}/utils/time.py
      - ./mounts/utils/pagination.py:${DEFAULT_SERVICE_DIR}/utils/pagination.py
      - ./mounts/utils/logging.py:${DEFAULT_SERVICE_DIR}/utils/logging.py
    networks:
      - verim_network
    restart: always

  celery-flower:
    image: mher/flower:2.0
    container_name: ${CONTAINER_PREFIX}-celery-flower
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      FLOWER_PORT: ${FLOWER_PORT}
      FLOWER_BASIC_AUTH: ${FLOWER_LOGIN}:${FLOWER_PASSWORD}
      FLOWER_URL_PREFIX: ${FLOWER_URL_PREFIX}
    depends_on:
      celery-worker:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5555:5555"
    networks:
      - verim_network
    restart: always

volumes:
  verim_rabbitmq_data:
    name: verim_rabbitmq_data
  verim_redis_data:
    name: verim_redis_data
