import os


ACCESS_SECRET_KEY = os.environ.get('ACCESS_SECRET_KEY', 'ACCESS_SECRET_KEY')  # FIXME
REFRESH_SECRET_KEY = os.environ.get('REFRESH_SECRET_KEY', 'REFRESH_SECRET_KEY')  # FIXME
ACCESS_TOKEN_LIFETIME = 8 * 60  # in minutes
REFRESH_TOKEN_LIFETIME = 48 * 60  # in minutes

TIMEZONE = 'Europe/Moscow'

PASSWORD_SALT_LENGTH = 20
PASSWORD_HASH_ITERATIONS = 100_100
