"""Add type column to code

Revision ID: 468e02e8c8e1
Revises: 1c1bbe5e0a97
Create Date: 2023-09-17 15:56:45.179204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468e02e8c8e1'
down_revision: Union[str, None] = '1c1bbe5e0a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_code', sa.Column('type', sa.String(length=14), nullable=False))
    op.create_unique_constraint(None, 'auth_code', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_code', type_='unique')
    op.drop_column('auth_code', 'type')
    # ### end Alembic commands ###
