"""Add ondelete CASCADE to code for user fk

Revision ID: 4b05e3dedb27
Revises: dc907e074359
Create Date: 2023-10-07 08:47:17.194058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b05e3dedb27'
down_revision: Union[str, None] = 'dc907e074359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('auth_code_user_id_fkey', 'auth_code', type_='foreignkey')
    op.create_foreign_key(None, 'auth_code', 'auth_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_code', type_='foreignkey')
    op.create_foreign_key('auth_code_user_id_fkey', 'auth_code', 'auth_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
