"""add user tokens revoked at

Revision ID: 788c2e702bd1
Revises: 18c7f0ebcf80
Create Date: 2023-09-10 12:03:09.870588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788c2e702bd1'
down_revision: Union[str, None] = '18c7f0ebcf80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tokens_revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tokens_revoked_at')
    # ### end Alembic commands ###
