"""Add email_confirmed column to user

Revision ID: dc907e074359
Revises: 468e02e8c8e1
Create Date: 2023-09-17 17:59:52.276375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc907e074359'
down_revision: Union[str, None] = '468e02e8c8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('email_confirmed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'email_confirmed')
    # ### end Alembic commands ###
