import os


TIMEZONE = os.environ.get("TIMEZONE")

AUTHENTICATION_HEADER = os.environ.get("AUTHENTICATION_HEADER")
AUTHENTICATION_HEADER_PREFIX = os.environ.get("AUTHENTICATION_HEADER_PREFIX")

MAIL_USERNAME = os.environ.get("MAIL_USERNAME")
MAIL_PASSWORD = os.environ.get("MAIL_PASSWORD")
MAIL_FROM = os.environ.get("MAIL_FROM")
MAIL_PORT = int(os.environ.get("MAIL_PORT"))
MAIL_SERVER = os.environ.get("MAIL_SERVER")
MAIL_FROM_NAME = os.environ.get("MAIL_FROM_NAME")

AUTH_GRPC_HOST = os.environ.get("AUTH_GRPC_HOST")
AUTH_GRPC_PORT = os.environ.get("AUTH_GRPC_PORT")

PUBLISHER_GRPC_HOST = os.environ.get("PUBLISHER_GRPC_HOST")
PUBLISHER_GRPC_PORT = os.environ.get("PUBLISHER_GRPC_PORT")

CONFIRMATION_CODE_LENGTH = int(os.environ.get("CONFIRMATION_CODE_LENGTH"))
