# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Create env file
      run: |
        echo "${{ vars.ENV_FILE }}" > .env
    - name: Build containers
      run: |
        docker-compose up -d auth
        docker-compose up -d gateway
        docker-compose up -d publisher
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        docker exec dev-verim-auth python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        docker exec dev-verim-gateway python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        docker exec dev-verim-publisher python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # docker exec dev-verim-auth python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        docker exec dev-verim-gateway python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        docker exec dev-verim-publisher python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    - name: Test with pytest
      run: |
        docker exec dev-verim-auth python -m pytest tests --doctest-modules --junitxml=junit/auth-test-results.xml --cov=. | tee auth-test-results.txt
        docker exec dev-verim-gateway python -m pytest tests --doctest-modules --junitxml=junit/gateway-test-results.xml --cov=. | tee gateway-test-results.txt
        docker exec dev-verim-publisher python -m pytest tests --doctest-modules --junitxml=junit/publisher-test-results.xml --cov=. | tee publisher-test-results.txt
        docker cp dev-verim-auth:/microservice/junit/auth-test-results.xml .
        docker cp dev-verim-auth:/microservice/junit/gateway-test-results.xml .
        docker cp dev-verim-auth:/microservice/junit/publisher-test-results.xml .
    - name: Pytest coverage comment
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        multiple-files: |
          Auth Coverage, ./auth-test-results.txt, ./auth-test-results.xml
          Gateway Coverage, ./gateway-test-results.txt, ./gateway-test-results.xml
          Publisher Coverage, ./publisher-test-results.txt, ./publisher-test-results.xml
        # pytest-coverage-path: ./auth-test-results.txt
        hide-badge: false
        hide-report: false
        create-new-comment: true
        hide-comment: false
        report-only-changed-files: true
        remove-link-from-badge: true
        # junitxml-path: ./auth-test-results.xml
  
    # Only on dev merge!!!
    - name: Pytest coverage badge
      # if: ${{ github.ref == 'refs/heads/dev' }}
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 757112fa1eaaf7bee58f771e2238c394
        filename: VerimDevCoverage.json
        label: Coverage Report
        message: ${{ steps.coverageComment.outputs.coverage }}
        color: ${{ steps.coverageComment.outputs.color }}
        namedLogo: python
    - name: Update Readme with Coverage Html
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: |
        sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
    - name: Commit & Push changes to Readme
      if: ${{ github.ref == 'refs/heads/dev' }}
      uses: actions-js/push@master
      with:
        message: Update coverage on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}
