# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: Create env file
      run: |
        echo "${{ vars.ENV_FILE }}" > .env
        cat .env
    - name: Build containers
      run: |
        ls -alh
        docker-compose up -d auth
        docker logs dev-verim-db
        # docker-compose up -d gateway
        # docker-compose up -d publisher
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        docker exec dev-verim-auth python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # docker exec dev-verim-gateway python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # docker exec dev-verim-publisher python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        docker exec dev-verim-auth python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        # docker exec dev-verim-gateway python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
        # docker exec dev-verim-publisher python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    - name: Test with pytest
      run: |
        docker exec dev-verim-auth pytest --cov
        # docker exec dev-verim-auth python -m pytest tests --doctest-modules --junitxml=junit/auth-test-results.xml --cov=com --cov-report=xml --cov-report=html
        # docker exec dev-verim-gateway python -m pytest tests --doctest-modules --junitxml=junit/gateway-test-results.xml --cov=com --cov-report=xml --cov-report=html
        # docker exec dev-verim-publisher python -m pytest tests --doctest-modules --junitxml=junit/publisher-test-results.xml --cov=com --cov-report=xml --cov-report=html
